language: cpp
dist: xenial
compiler: gcc

before_install:
- sudo pip install codecov
- sudo apt-get install qt4-qmake
- sudo apt-get install libqt4-dev

script: 
- qmake
- make --silent
- ./test.pro
# Codecov
- ./get_code_cov
- codecov

after_success:
# Codecov
- bash <(curl -s https://codecov.io/bash)
