version: 2.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_gcc_6:
    docker:
      - image: chooseyourplan/circleci_custom_build
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
      - run: apt-get install lcov

      - run: lcov --list coverage.info 
      - run: lcov --capture --directory . --output-file coverage.info
      - run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
