version: 2.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_gcc_6:
    docker:
      - image: 88plug/gcc-8-ubuntu-18.04
    working_directory: ~/my-app
    steps:
      - checkout
      - run: g++ -v
      - run: apt-get install sudo -y
      - run: apt-get install bash -y
      - run: sudo apt-get update --fix-missing
      - run: apt-get install lcov -y
      - run: apt-get install curl -y
      - run: g++-8 -std=c++17 -g -O0 -Wall -Wextra --coverage -o TestCase test.cpp entry.cpp database.cpp 
      - run: sudo ./TestCase
      - run: gcov test.cpp
      - run: gcov database.cpp
      - run: gcov entry.cpp
      - run: ls -la
      - run: bash <(curl -s https://codecov.io/bash)
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
