version: 2.0
jobs:
  build_gcc_test_benchmarks:
    docker:
      - image: gcc:8
    steps:
      - checkout
      - run: make
      - run: ./myprog --benchmark-samples 1000

      - run: bash <(curl -s https://codecov.io/bash) -t 880fe762-07c1-4469-ab15-b46876d824da -f "!catch.hpp"
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
      - run: ./myprog
      - run: bash <(curl -s https://codecov.io/bash) -t 880fe762-07c1-4469-ab15-b46876d824da -f "!catch.hpp"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_test_benchmar_test_benchmarks
      - build_gcc_latest
