version: 2.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_gcc_6:
    docker:
      - image: chooseyourplan/circleci_custom_build
    steps:
      - checkout
      - run: apt-get install -y sudo
      - run: g++ -std=c++17 -Wall -Wextra --coverage -o TestCase test.cpp entry.cpp database.cpp 
      - run: sudo ./TestCase
      
      - run: lcov --capture --directory . --output-file coverage.info
      - run: ls
      - run: cat coverage.info
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.info -t 880fe762-07c1-4469-ab15-b46876d824da
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
