version: 2.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_gcc_6:
    docker:
      - image: 88plug/gcc-8-ubuntu-18.04
    working_directory: ~/my-app
    steps:
      - checkout
      - run: g++ -v
      - run: apt-get install sudo -y
      - run: sudo apt-get update --fix-missing
      - run: apt-get install lcov -y
      - run: mkdir build
      - run: pwd
      - run: cd build && cp ../sample.txt .
      - run: g++-8 -std=c++17 -Wall -Wextra --coverage -o TestCase /root/myapp/test.cpp /root/myapp/entry.cpp /root/myapp/database.cpp 
      - run: sudo ./TestCase
      - run: sudo gcov-8 test.gcno
      - run: sudo gcov-8 entry.gcno
      - run: sudo gcov-8 databse.gco
      - run: bash <(curl -s https://codecov.io/bash) -t 880fe762-07c1-4469-ab15-b46876d824da
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
