version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
- build_gcc_latest
