version: 2.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_gcc_6:
    docker:
      - image: chooseyourplan/circleci_custom_build:gcc8
    working_directory: ~/my-app
    steps:
      - checkout
      - run: g++ -v
      - run: apt-get install sudo -y
      - run: apt-get install lcov -y
      - run: g++ -std=c++17 -g -Wall -Wextra --coverage -o TestCase test.cpp entry.cpp database.cpp 
      - run: sudo ./TestCase
      - run: sudo gcov test.gcno
      - run: sudo lcov --capture --base-directory . --directory . --output-file coverage.info --rc lcov_branch_coverage=1 -c -o coverage.info
      - run: chmod +x coverage.info
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.info -t 880fe762-07c1-4469-ab15-b46876d824da
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ -std=c++17 -Wall -Wextra -o TestCase test.cpp entry.cpp database.cpp 
      - run: ./TestCase
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
